# Generated by Django 5.1.3 on 2025-01-22 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbuddiesapp', '0002_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_pic', models.ImageField(upload_to='book_covers/')),
                ('description', models.TextField()),
                ('book_file', models.FileField(upload_to='book_files/')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookbuddiesapp.genre')),
            ],
        ),
    ]
