# Generated by Django 5.1.3 on 2025-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbuddiesapp', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='genre_images/'),
        ),
    ]
