# Generated by Django 5.1.3 on 2025-01-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookbuddiesapp', '0004_genre_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
