# Generated by Django 5.1.3 on 2025-02-19 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbuddiesapp', '0010_purchasedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedbook',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
